version: '3'

volumes:
  local_postgres_data: {}
services:
  django: &django
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: api
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.database
    ports:
      - "8000:8000"
  
  postgres:
    image: postgres:16.0-alpine3.17
    env_file:
      - ./.envs/.database
    volumes:
      - local_postgres_data:/var/lib/postgresql/data